diff --git a/./ffmpeg/Makefile b/./local_setup/Makefile
index 1fb742f..b832b20 100644
--- a/./ffmpeg/Makefile
+++ b/./local_setup/Makefile
@@ -46,9 +46,29 @@ FF_EXTRALIBS := $(FFEXTRALIBS)
 FF_DEP_LIBS  := $(DEP_LIBS)
 FF_STATIC_DEP_LIBS := $(STATIC_DEP_LIBS)
 
+AFL_DRIVER_OBJS := afl_driver.o
+AFL_DRIVER_LIB := libafl_driver.a
+
 $(TOOLS): %$(EXESUF): %.o
 	$(LD) $(LDFLAGS) $(LDEXEFLAGS) $(LD_O) $^ $(EXTRALIBS-$(*F)) $(EXTRALIBS) $(ELIBS)
 
+orig_target_dec_%_fuzzer$(EXESUF): orig_target_dec_%_fuzzer.o $(FF_DEP_LIBS)
+	$(LD) $(LDFLAGS) $(LDEXEFLAGS) $(LD_O) $^ $(ELIBS) $(FF_EXTRALIBS) $(LIBFUZZER_PATH)
+
+tools/afl_driver.o: tools/afl_driver.cpp
+	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@
+
+tools/afl_driver.a: tools/afl_driver.o
+	$(AR) $(ARFLAGS) $@ $<
+
+tools/target_dec_h264_fuzzer$(EXESUF): tools/target_dec_h264_fuzzer.o $(FF_DEP_LIBS) # tools/afl_driver.a
+	$(LD) $(LDFLAGS) $(LDEXEFLAGS)  $(LD_O) $^ -o $@ $(ELIBS) $(FF_EXTRALIBS) $(LIBFUZZER_PATH)
+
+#
+#target_dec_%_fuzzer$(EXESUF): target_dec_%_fuzzer.o $(FF_DEP_LIBS) libafl_driver.a
+#	$(LD) $(LDFLAGS) $(LDEXEFLAGS) $(LD_O) $^ -o $@ $(ELIBS) $(FF_EXTRALIBS) $(LIBFUZZER_PATH)
+
+
 target_dec_%_fuzzer$(EXESUF): target_dec_%_fuzzer.o $(FF_DEP_LIBS)
 	$(LD) $(LDFLAGS) $(LDEXEFLAGS) $(LD_O) $^ $(ELIBS) $(FF_EXTRALIBS) $(LIBFUZZER_PATH)
 
@@ -72,6 +92,7 @@ tools/scale_slice_test$(EXESUF): ELIBS = $(FF_EXTRALIBS)
 tools/sofa2wavs$(EXESUF): ELIBS = $(FF_EXTRALIBS)
 tools/uncoded_frame$(EXESUF): $(FF_DEP_LIBS)
 tools/uncoded_frame$(EXESUF): ELIBS = $(FF_EXTRALIBS)
+tools/orig_target_dec_%_fuzzer$(EXESUF): $(FF_DEP_LIBS)
 tools/target_dec_%_fuzzer$(EXESUF): $(FF_DEP_LIBS)
 tools/target_dem_%_fuzzer$(EXESUF): $(FF_DEP_LIBS)
 
@@ -156,11 +177,19 @@ uninstall: uninstall-data uninstall-headers uninstall-libs uninstall-pkgconfig
 uninstall-data:
 	$(RM) -r "$(DATADIR)"
 
+#clean::
+#	$(RM) $(CLEANSUFFIXES)
+#	$(RM) $(addprefix compat/,$(CLEANSUFFIXES)) $(addprefix compat/*/,$(CLEANSUFFIXES)) $(addprefix compat/*/*/,$(CLEANSUFFIXES))
+#	$(RM) -r coverage-html
+#	$(RM) -rf coverage.info coverage.info.in lcov
+
 clean::
 	$(RM) $(CLEANSUFFIXES)
 	$(RM) $(addprefix compat/,$(CLEANSUFFIXES)) $(addprefix compat/*/,$(CLEANSUFFIXES)) $(addprefix compat/*/*/,$(CLEANSUFFIXES))
 	$(RM) -r coverage-html
 	$(RM) -rf coverage.info coverage.info.in lcov
+	$(RM) afl_driver.a  # Add this line to remove afl_driver.a file
+
 
 distclean:: clean
 	$(RM) .version config.asm config.h config_components.h mapfile  \
